logging.level.: DEBUG
spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/BOOKSTORE"
    username: "root"
    password: ""
    driver-class-name: "org.mariadb.jdbc.Driver"

  jpa:
    database-platform: "org.hibernate.dialect.MariaDBDialect"
    hibernate:
      ddl-auto: "update"
  # Docs: 
  #https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html
  #To use the issuer-uri property, it must also be true that one of idp.example.com/issuer/.well-known/openid-configuration, idp.example.com/.well-known/openid-configuration/issuer, or idp.example.com/.well-known/oauth-authorization-server/issuer is a supported endpoint for the authorization server. This endpoint is referred to as a Provider Configuration endpoint or a Authorization Server Metadata endpoint. 

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://dev-p7gb27xlils7dwl0.us.auth0.com/"
          jwk-set-uri: "https://dev-p7gb27xlils7dwl0.us.auth0.com/.well-known/jwks.json"

